name: Build Flatpak

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3

      - name: Build using Flatpak Builder
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Mixtapes-${{ matrix.arch }}.flatpak
          manifest-path: com.pocoguy.Muse.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mixtapes-${{ matrix.arch }}-flatpak
          path: Mixtapes-${{ matrix.arch }}.flatpak
